[build]
  publish = "public"          # Directory containing static assets (like index.html)
  functions = "netlify/functions"  # Serverless functions directory

[[redirects]]
  from = "/short"
  to = "/functions/short.js"
  status = 200

[[redirects]]
  from = "/:id"
  to = "/functions/redirect.js"
  status = 200
